### ISSUE TITLE
Inline & Overall Comment Deletion

### ISSUE THREAD

**Issue by gmeben** [MESH-Research/Pilcrow#1034]
When commenters leave an inline or overall comment by accident, there's no way for them to delete the comment.

Add comment deletion functionality so that users can delete thier own comments. Add a new "Delete" option to comment menu dropdowns. In the same way as comment modification, ensure that users can only delete their own comments and not the comments of others.

**Review Checklist**

* Users can delete their own comments
* Replies to deleted comments remain visible
* Deleted comments with replies are replaced with a message indicating their deletion
* Users cannot delete the comments of others
* Necessary backend unit testing has been added
* Necessary integration testing has been added

**Accessibility Checklist**

* No new color contrast issues are introduced
* Changed text has a font size of at least 16px
* Changed text uses plain language

**Comment by gmeben** [comment]
Takeaways from today's discussion: 

We're trying to gather feedback from the greater community on how deleted comment threads should be handled.

**Comment by gmeben** [comment]
Feedback gathered so far indicates a clear preference: maintain the visibility of the replies of deleted threads but replace the first post in the thread that has been deleted. There has also been some support for making this behavior configurable.

**Comment by sattler9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pilcrow-Development-5ff39ba363391e0019713c87/issues/MESH-Research/Pilcrow/1034?planning-poker) with Zenhub @sattler9 @gmeben @vilagshe
