### ISSUE TITLE
Toggling Dark Mode on the Submission Review Page

### ISSUE THREAD

**Issue by gmeben** [MESH-Research/Pilcrow#1036]
### Problem/Why
Some folks prefer a "dark mode" when using an application. The CCR app only has a "light mode"

### Goal/What
Build and implement a "dark mode" so that after clicking on the toggle button on the review submission page, the overall color scheme of the application toggles between light/dark.

### Solution/How
Implement the Quasar native dark mode configuration and customize as necessary to fix spots throughout that do not pass AA WCAG color contrast. The toggle setting can be session based. 

### To Do / Acceptance Criteria

- [x] Implement dark mode
- [ ] Add dark mode color changes and accessibility guides to the Style Guide

### Review Checklist

- [ ] The site toggles between light mode and dark mode upon clicking the toggle button on the Submission Review page
- [ ] The Style Guide is updated with Dark mode colors

### Accessibility Checklist

- [ ] All colors pass AA WCAG color contrast

**Comment by sattler9** [comment]
Grant shared this link: https://quasar.dev/style/dark-mode

**Comment by sattler9** [comment]
Need to determine whether we want this only for the review page, be only for the whole site, or both

**Comment by sattler9** [comment]
Need to determine whether we want this only for the review page, be only for the whole site, or both

**Comment by vilagshe** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pilcrow-Development-5ff39ba363391e0019713c87/issues/MESH-Research/CCR/1036?planning-poker) with Zenhub @gmeben @sattler9 @Sruthin86 @vilagshe @wreality
