### ISSUE TITLE
Change file upload input to accept only a single file

### ISSUE THREAD

**Issue by wreality** [MESH-Research/Pilcrow#1063]
### Problem/Why
A user uploading multiple files as part of a submission may be supported in the future, but the implementation details for how the application should interpret each file and what the user expectation would be if multiple files are uploaded is not defined.  

### Goal/What
The frontend input and the graphql API should only accept a single file as input.  The hasMany relationship of submission_files should remain as there is a likelihood of future support for multiple files attached to a submission.  

### To Do / Acceptance Criteria

- [x] Update the front end user upload input to only allow uploading a single file.  
- [x] Update the graphql schema to only accept a single uploaded file.

### Review Checklist

- [ ]  Only a single uploaded file is allowed

**Comment by wreality** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCR-Development-5ff39ba363391e0019713c87/issues/MESH-Research/CCR/1063?planning-poker) with ZenHub @gmeben @sattler9 @Sruthin86

**Comment by sattler9** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCR-Development-5ff39ba363391e0019713c87/issues/MESH-Research/CCR/1063?planning-poker) with ZenHub @wreality
