### ISSUE TITLE
Submission Export

### ISSUE THREAD

**Issue by gmeben** [MESH-Research/Pilcrow#1263]
### Problem/Why
Currently, no user can export the contents of a submission from the application to an outside location, such as Manifold or Fulcrum. It may not even be technically feasible to do so, and not all publications may have a need to export to such platforms. All submission content is stuck in the application. 

### Goal/What
Add functionality to export a standalone HTML file of the submission contents. It's possible other formats may be used, but HTML will be the primary exported file type. 

### Solution/How
Add a new page to handle submission export functionality. Add conditionally displayed elements that appear for allowed roles to access this new submission export page. For this initial iteration, those allowed roles are:

* Administrators
* Editors
* Review Coordinators
* Submitters

This allowed role list can be later made to be customizable by publication managers in a publication's settings so that these can be configured according to a publication's particular practices with regard to sharing submission content. 

The second condition for these elements is that the submission status be one of the following:

* Rejected
* Resubmission Requested
* Accepted as Final
* Archived
* Expired

The text content of these conditionally displayed elements to access the submission export page should read "Export Submission". These should appear:

* On a submission's review page
* On a submission's details page
* Within the action menu in submission/review tables

The submission export page should include a concise description of what format(s) to expect the download and a button to download the submission. As a bonus, add and some visual indicators for when a download is in progress and finished. 

### To Do / Acceptance Criteria

- [x] Add `SubmissionExport` page and route
- [x] Add interactive elements to access the new page
- [x] Add Cypress testing to assert that elements appear as necessary
- [x] Update ~~backend~~ client as necessary to enable downloads of the saved submission content

### Review Checklist

- [ ] The contents of a submitted manuscript can be exported to HTML after its review is completed

### Accessibility Checklist

- [ ] All added copy uses plain language
- [ ] No new a11y violations are introduced as detected by axe DevTools

**Comment by gmeben** [comment]
I'm saving these links to related documentation on Manifold for posterity: 

**Manifold**
* [Manifold API Docs](https://manifoldscholar.github.io/manifold-docusaurus/docs/developers/api)
* [swagger.json](https://github.com/ManifoldScholar/manifold/blob/master/api/public/api/static/docs/v1/swagger.json)
* [Adding Texts](https://manifoldscholar.github.io/manifold-docusaurus/docs/backend/texts/#adding-texts)

**Comment by sattler9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pilcrow-Development-5ff39ba363391e0019713c87/issues/MESH-Research/Pilcrow/1263?planning-poker) with Zenhub @gmeben @vilagshe @wreality

**Comment by gmeben** [comment]
It has been suggested that the new Export page should also include the option to export the metadata associated with submissions, such as lists of the submitters, in order to make easier the process of transferring information out of Pilcrow into a platform like Humanities Commons.

**Comment by gmeben** [comment]
There are a number of potential formats that could be useful for those trying to enter the metadata of submissions into other platforms. Those formats are:

* [DataCite](https://schema.datacite.org/meta/kernel-4.4/) (XML)
* [ONIX](https://www.editeur.org/83/Overview/) (XML)
    - [Documentation](https://www.loc.gov/preservation/digital/formats/fdd/fdd000488.shtml#:~:text=The%20ONIX%20for%20Books%20file,retailers%2C%20and%20supply%20chain%20partners.)
    - [Latest Codelist](https://ns.editeur.org/onix/en)
* [DublinCore](https://www.dublincore.org/schemas/)(XML)
* HTML
