### ISSUE TITLE
Visualize the Submissions Page as a Table

### ISSUE THREAD

**Issue by vilagshe** [MESH-Research/Pilcrow#1333]
### Problem/Why
The Submissions page is not currently optimized to display relevant information about each submission, such as the submission status. 

### Goal/What
Visualize the Submissions page as a table with the most relevant information about each submission displayed. Seeing the data for each submission displayed as a table would make it easier to sort submissions by status, enabling reviewers to focus on submissions that need to be reviewed, for example.

### Solution/How

Utilize the `SubmissionTable` component and supply it with the existing data list of all submissions on the Submissions page.

### To Do / Acceptance Criteria

- [x] Create a new design of the Submissions page

### Review Checklist

- [x] Submissions are represented in a tabular fashion in the design(s)

### Accessibility Checklist

- [x] Hyperlinks are attached to this issue of the deliverable design(s)

**Comment by sattler9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pilcrow-Development-5ff39ba363391e0019713c87/issues/MESH-Research/Pilcrow/1333?planning-poker) with Zenhub @gmeben @stephanievaskomsu @vilagshe

**Comment by vilagshe** [comment]
Wireframe: https://xd.adobe.com/view/b729ae87-d546-4871-a789-2282c3959b56-e27a/

**Comment by gmeben** [comment]
I checked off the review and accessibility items. Given today's team review, I think this issue can be considered complete.
