### ISSUE TITLE
Adapt Status Changing Buttons for Mobile

### ISSUE THREAD

**Issue by gmeben** [MESH-Research/Pilcrow#1336]
### Problem/Why
Currently, the controls to change a submission's status on the Submission Review page don't adapt for small viewports.

![Screenshot of the cramped buttons for changing's a submission status within the toolbar on the Submission Review page](https://images.zenhubusercontent.com/5ff7670b9384a948b4663b2d/a92fbaad-676b-4a92-94e2-b2a9850342e1)

### Goal/What
Implement the design from the [Mobile layout on Miro](https://miro.com/app/board/uXjVOmu9G8w=/?moveToWidget=3458764529600382120&cot=14) so that the status changing buttons collapse into an expandable component. 

![Screenshot of the proposed collapsable design for the status changing buttons](https://images.zenhubusercontent.com/5ff7670b9384a948b4663b2d/b65fe2b4-1366-4cd4-9595-e08bacb5a83a)

### Solution/How
Update the Vue template for `SubmissionToolbar` to support the new collapsable/expandable component functionality. 

### To Do / Acceptance Criteria

- [x] Update `SubmissionToolbar` template

### Review Checklist

- [ ] The same options appear on smaller device viewports as they do for larger viewports

### Accessibility Checklist

- [ ] Sizes of buttons are of sufficient scale to comfortably support tap interactions on mobile devices
- [ ] axe DevTools automated testing detects new errors

**Comment by sattler9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pilcrow-Development-5ff39ba363391e0019713c87/issues/MESH-Research/Pilcrow/1336?planning-poker) with Zenhub @gmeben @wreality @stephanievaskomsu
