### ISSUE TITLE
Rename CCR to Pilcrow in GitHub and App

### ISSUE THREAD

**Issue by gmeben** [MESH-Research/Pilcrow#1652]
### Problem/Why
The application has been renamed from CCR to Pilcrow, however, "CCR" as it refers to the application still publicly appears throughout the repository page on GitHub as well as throughout the application itself.

### Goal/What
Rename all references of the application's old name "CCR" to "Pilcrow" on the pages in the GitHub repository as well as the application code. Appearances of "CCR" as they refer to the peer review process (formerly "Formative Peer Review") should remain unchanged.

### Solution/How
Navigate throughout the GitHub repository for the application and rename all instances of the old application name found within [Wiki pages](https://github.com/MESH-Research/CCR/wiki), repository descriptions and [settings](https://github.com/MESH-Research/CCR/settings), and any [README files](https://github.com/MESH-Research/CCR/blob/master/README.md). Also update references within the code itself for the application site in the [root directory](https://github.com/MESH-Research/CCR), [backend directory](https://github.com/MESH-Research/CCR/tree/master/backend), and [client directory](https://github.com/MESH-Research/CCR/tree/master/client), as well as the documentation site in the [docs directory](https://github.com/MESH-Research/CCR/tree/master/docs). 

### To Do / Acceptance Criteria

- [x] Update the GitHub repository
- [x] Update the application and docs site

### Review Checklist

- [ ] All instances of the old application name have been renamed=

**Comment by gmeben** [comment]
It was noted in today's meeting that this renaming is likely to have ramifications for integrated services that use this repository, like Zenhub and Range.

**Comment by wreality** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCR-Development-5ff39ba363391e0019713c87/issues/MESH-Research/CCR/1652?planning-poker) with Zenhub @gmeben @sattler9 @Sruthin86 @vilagshe
