### ISSUE TITLE
Improve Documentation for Copyediting

### ISSUE THREAD

**Issue by gmeben** [MESH-Research/Pilcrow#1655]
### Problem/Why
The current process for updating the copy on the application and docs site is not as clear as it could be. Accessing the latest artifact of screenshots is not obvious and not visualized in the documentation. The documentation for the default pull request title keyword is improperly specified as "docs" even though copyediting changes can take place outside of the documentation site. The link in the documentation to [the file that's used for copyediting](https://github.com/MESH-Research/CCR/blob/master/client/src/i18n/en-US/index.js) has been changed and will no longer work. 

### Goal/What
Update the documentation for copyediting so that the process is more clear.

### Solution/How
Change the default pull request title keyword from "docs" to "feat". Break out the steps involved for downloading screenshots and include images to illustrate the parts that are more difficult to visualize. Fix the URL to the new JSON file.

### To Do / Acceptance Criteria

- [x] Update the documentation for copyediting

### Review Checklist

- [x] The documentation is more clear than it was previously

### Accessibility Checklist

- [x] Language added uses [plain language](https://sheribyrnehaber.com/plain-language-essential-for-content-accessibility/)

**Comment by sattler9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pilcrow-Development-5ff39ba363391e0019713c87/issues/MESH-Research/CCR/1655?planning-poker) with Zenhub @gmeben @Sruthin86 @vilagshe @wreality @stephanievaskomsu
