### ISSUE TITLE
Fix Available Options for Submissions Accepted as Final

### ISSUE THREAD

**Issue by gmeben** [MESH-Research/Pilcrow#1674]
**Describe the bug**

**To Reproduce**
1. Log in as a review coordinator (`reviewCoordinator@pilcrow.dev`)
2. Visit a submission with a status of "Accepted as Final" (`/submission/105/review`)
3. Click the "Status Options" dropdown
4. Note that the available options are inappropriate ("Accept as Final")

**Expected behavior**
The status change options available for a submission with a status of "Accepted as Final" should not include inappropriate options as is included for a submission with a status of "Under Review" or "Awaiting Decision". It should only include:

* Archive
* Delete

**Screenshots**
![pilcrow.lndo.site_submission_114_review.png](https://images.zenhubusercontent.com/5ff7670b9384a948b4663b2d/e658a35c-2813-4af4-849f-015a7e60f7ae)

**Comment by vilagshe** [comment]
Work completed so far:
- Options updated to archive, delete
- Confirm Status dialog updated

Work to do:
- Get the submission status to change to archived/deleted

**Comment by vilagshe** [comment]
Work Completed so far:
- Status change options updated
- Confirm Status Change Dialog updated
- Status successfully changes

Work to do:
- Cypress testing
