### ISSUE TITLE
Submission Title Modification

### ISSUE THREAD

**Issue by gmeben** [MESH-Research/Pilcrow#1735]
### Problem/Why
After a submission is uploaded/created, there is no way in the application for a user to modify the submission's title. This can be an issue for those who wish to correct mistakes in or improve a submission's title.

### Goal/What
Enable functionality that allows a user with sufficient privilege (submitter, review coordinator, editor, or administrator) to modify a submission's title.

### Solution/How
Update `SubmissionPolicy.php` for updating the submission's title so that only the intended roles are allowed to modify the title. Update the GraphQL endpoint to use `SubmissionPolicy.php` for updating a submission title's. Modify and add functionality to the Vue template for the Submission Details page to use this updated endpoint for modifying a submission's title. Add validation on the backend and frontend to ensure that the title is a maximum of 512 characters and is not empty. 

### To Do / Acceptance Criteria

- [x] Update `SubmissionPolicy.php` and utilize this policy in the GraphQL endpoint
- [x] Update the Submission Details Vue template with necessary components and functionality
- [x] Add validation
- [x] Add PHPUnit testing to ensure API works as expected
- [x] Add Cypress testing to ensure feature works as expected

### Review Checklist

- [ ] A submission's title can be modified by a submitter of the submission
- [ ] A submission's title cannot be modified by a reviewer of the submission

### Accessibility Checklist

- [ ] Modifying the title can be done solely with a keyboard

**Comment by sattler9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pilcrow-Development-5ff39ba363391e0019713c87/issues/MESH-Research/Pilcrow/1735?planning-poker) with Zenhub @gmeben @vilagshe
