### ISSUE TITLE
Wireframe Basic Dashboard Elements

### ISSUE THREAD

**Issue by vilagshe** [MESH-Research/Pilcrow#1738]
Problem/Why
When any user logs in to the application, they are redirected to a page titled "My Dashboard" that is completely blank. This is the experience of submitters, reviewers, review coordinators, editors, and administrators. Therefore, this page is not useful and can give the impression that the application is incomplete.

Goal/What

Create wireframes for basic elements to go on the Dashboard page based on feedback received for what is desired on the page for a Reviewer, an Author, and a Review Coordinator.

Reviewer:
- Be able to see reviews participating in, their statuses, (due dates), anything that needs call to action

Review Coordinator:
- Be able to see reviews coordinating, their statuses, (due dates), anything that needs call to action

Author:
- Be able to see active submissions, their status, anything that needs call to action

Include a section that links to the docs (our guide)
"New to Pilcrow? Learn more in our guide[https://pilcrow.meshresearch.dev/guide/]" w/ our guide as the link

To Do / Acceptance Criteria
 Wireframes are created displaying basic dashboard elements for Reviewers, Review Coordinators, and Authors

**Comment by vilagshe** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pilcrow-Development-5ff39ba363391e0019713c87/issues/MESH-Research/Pilcrow/1738?planning-poker) with Zenhub @gmeben @sattler9 @Sruthin86 @wreality

**Comment by vilagshe** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pilcrow-Development-5ff39ba363391e0019713c87/issues/MESH-Research/Pilcrow/1738?planning-poker) with Zenhub @stephanievaskomsu

**Comment by gmeben** [comment]
These are links to the deliverables:

* Author Dashboard: https://xd.adobe.com/view/dbe1b864-2527-41d2-a2d9-f854bd22fe66-8eb2/screen/bd8ac0a1-a2b6-4404-8229-49edafc090b3/
* Reviewer Dashboard: https://xd.adobe.com/view/6d3d9a4a-17a7-447d-a15a-53e298038a64-386e/
* Review Coordinator Dashboard: https://xd.adobe.com/view/9ec3b9c6-9ebd-4f62-a3b6-b8a8ab84ea0f-cb90/screen/2df5ff44-8703-4624-9fa2-71fc31a40101/
