### ISSUE TITLE
Seed More Submissions in Different States

### ISSUE THREAD

**Issue by gmeben** [MESH-Research/Pilcrow#1767]
### Problem/Why
The current selection of seeded sample submissions in the application are as follows:

* Under Review
* Initially Submitted
* Rejected
* Resubmission Requested
* Draft
    - Created under regularuser@pilcrow.dev

The following other possible states are missing from being showcased in the application:

* ~~Resubmitted~~ (defunct)
* Awaiting Review
* Accepted as Final
* Expired
* Awaiting Decision
* ~~Revision Requested~~ (defunct)
* Archived
* Deleted

### Goal/What
Add a seeded submission for each of the missing submission states so that all are represented.

### Solution/How
Extend `SubmissionSeeder.php` with new submissions for each of the missing states documented above.

### To Do / Acceptance Criteria

- [x] Extend `SubmissionSeeder.php`

### Review Checklist

- [ ] All possible submission states are represented in the application

### Accessibility Checklist

- [ ] axe DevTools detects no new accessibility violations introduced

**Comment by gmeben** [comment]
This issue was created as a result from today's team time discussion.

**Comment by sattler9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pilcrow-Development-5ff39ba363391e0019713c87/issues/MESH-Research/Pilcrow/1767?planning-poker) with Zenhub @gmeben @stephanievaskomsu @wreality
