### ISSUE TITLE
Home Page Design

### ISSUE THREAD

**Issue by gmeben** [MESH-Research/Pilcrow#1770]
### Problem/Why
Currently, the home page for Pilcrow only advertises the application's front end framework, Quasar.

![Screenshot of the current home page that only features the page title and the Quasar logo](https://images.zenhubusercontent.com/5ff7670b9384a948b4663b2d/63a61e1f-97ea-4844-8696-2d1a79c4c9ac)

This misses an opportunity to feature more relevant content for users, such as overviews of the application, showcases of features, and so on. The current home page is not useful. 

### Goal/What
Create an improved and useful home page design.

### Solution/How
Develop a list of suitable content for the home page. Create a design that suits the needs of this content. 

### To Do / Acceptance Criteria

- [x] Create a list of suitable content
- [x] Design
- [x] Share with the team to discuss potential future iterations or accept the design as is

### Review Checklist

- [x] The home page design features all specified content

### Accessibility Checklist

- [x] Text content is legible, readable, and uses plain language

**Comment by gmeben** [comment]
We decided in today's team meeting that this will be handed over to community engagement.

**Comment by sattler9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pilcrow-Development-5ff39ba363391e0019713c87/issues/MESH-Research/Pilcrow/1770?planning-poker) with Zenhub @gmeben @stephanievaskomsu @vilagshe

**Comment by stephanievaskomsu** [comment]
https://xd.adobe.com/view/29083090-64a2-49f0-9706-d41dbcfecbfb-7c5b/

Only fiddly issue I am having---In the actual, can we make the hyperlinks a blue shade in our palette?

**Comment by gmeben** [comment]
@stephanievaskomsu Yep, we can make the links blue. They'll likely be the `primary` color in our color palette, which will differ slightly between light and dark mode: https://github.com/MESH-Research/Pilcrow/wiki/Style-Guide---in-the-making#color

**Comment by stephanievaskomsu** [comment]
Works for me! Thanks!
