### ISSUE TITLE
Adjust Conversion of End Notes and References

### ISSUE THREAD

**Issue by gmeben** [MESH-Research/Pilcrow#1771]
### Problem/Why
Currently, Pandoc does not separate references from end/footnotes. For ease of review, it would be nice to have a bibliography section and a note section that are separate.

Also brings up a larger issue: journals often have different ways that they accept citations. Are we going to make sure that in the guide for each journal there is a space for specifying how bibliographies and citations and annotations should be put into draft submissions?

### Goal/What
* The conversion will be based on what is capable of being done with Pandoc. 
* Add better delineation between references and footnotes (a title perhaps)
* Add working hyperlinks between footnote references and footnotes so that a user can jump between them

### To Do / Acceptance Criteria

- [ ]

### Review Checklist

- [ ]

### Accessibility Checklist

- [ ]

**Comment by wreality** [comment]
Closing with the note that pandoc doesn't separate references and endnotes in it's parsing, so treating them differently is currently not possible unfortunately.
