### ISSUE TITLE
Create Accounts and Seed Articles for Review For Usability Testing

### ISSUE THREAD

**Issue by stephanievaskomsu** [MESH-Research/Pilcrow#1772]
### Problem/Why
We are nearing usability testing time and need accounts for each one of our testers that will let them test profile, review, and submission.

### Goal/What
Five accounts with access to five different copies of the same article to review. Testers cannot see each others work. System must also be in the same state for all users.

### To Do / Acceptance Criteria

- [ ] Create 5 account profiles (tester 1, tester 2, ...) with reviewer permission level
- [ ] Upload Chris's article 5 times coordinated in name with each tester

### Review Checklist

- [ ]

### Accessibility Checklist

- [ ]

**Comment by sattler9** [comment]
A whole new environment will be spun up to host these.
