### ISSUE TITLE
Clarify Filtering of Reviews on Reviews Page

### ISSUE THREAD

**Issue by gmeben** [MESH-Research/Pilcrow#1778]
### Problem/Why
Currently, submissions that are in certain states will not appear in the "To Review" section on the Reviews page. This filtering is not obvious. The filtered states are:

* Draft
* Initially Submitted
* Awaiting Review

The omission of these records on the Reviews page can lead to confusion among reviewers who may expect to access the individual reviews of these submission from the Reviews page.

### Goal/What
Make it clear what reviews are filtered on the Reviews page. 

Consider adding a helpful text popup explaining what states are filtered and what states are not.

### Solution/How
A section or popup is added to the page that indicates which states of submissions will appear on the Reviews page and which will not.

### To Do / Acceptance Criteria

- [x] Add a section or popup explaining which states are filtered on the Reviews page and which are not

### Review Checklist

- [ ] Help text outlining which reviews will appear on the Reviews page is present

### Accessibility Checklist

- [ ] No new A11y errors are introduced

**Comment by sattler9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pilcrow-Development-5ff39ba363391e0019713c87/issues/MESH-Research/Pilcrow/1778?planning-poker) with Zenhub @gmeben @vilagshe @wreality
