### ISSUE TITLE
Add dismiss button to all notify popups

### ISSUE THREAD

**Issue by wreality** [MESH-Research/Pilcrow#1804]
### Problem/Why
There is inconsistency with the notify popups in the application in that some have dismiss buttons and others do not.
![image](https://user-images.githubusercontent.com/463159/230175429-eaccad7a-87f6-4501-911e-36e4054d16b2.png)
![image](https://user-images.githubusercontent.com/463159/230175593-4cf9109b-626e-46a3-9856-633b7ab6e3e0.png)

### Goal/What
We should standardize the notify popups and ensure that they all have dismiss buttons and UI indicating how long until they are autodismissed.  This is helpful for integration testing to be able to clear the popup rather than waiting for it to disappear as well as for users to have the functionality available consistently.

### Solution/How
Create a composition function for displaying a popup notification to standardize how various components use the UI.

### To Do / Acceptance Criteria

- ~~[x] Create notification composable~~
- [x] Replace adhoc notification popup calls with the created composable.
- [ ] Update any tests that are waiting on the notify popup to disappear based on timeout

### Review Checklist

- [ ] All notification popups have dismiss buttons.

### Accessibility Checklist

- [ ] Dismiss button should have appropriate aria / accessibility attributes.

**Comment by sattler9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pilcrow-Development-5ff39ba363391e0019713c87/issues/MESH-Research/Pilcrow/1804?planning-poker) with Zenhub @gmeben @vilagshe @wreality

**Comment by vilagshe** [comment]
Notify popups are defined in two different ways:
1. using `notify()`, Icon: "done", Close UI: none
![image](https://github.com/MESH-Research/Pilcrow/assets/108834493/5586ddc3-7ffb-4947-bffb-3436c454ce1d)

```vue.js
notify({
      color: "positive",
      message: t(`dialog.confirmStatusChange.statusChanged.${props.action}`),
      icon: "done",
      attrs: {
        "data-cy": "change_status_notify",
      },
    })
```


2. using `newStatusMessage()`, Icon: "success", Close UI: "CLOSE", Utilizes `useFeedbackMessages()` to get Close UI
![image](https://github.com/MESH-Research/Pilcrow/assets/108834493/09ba750b-5a5b-4fff-9d75-6d921eaf4857)

```vue.js
const { newStatusMessage } = useFeedbackMessages({
  attrs: {
    "data-cy": "submission_title_notify",
  },
})

function checkThatFormIsInvalid() {
  let failureMessage = false

  if (newPubV$.value.required.$invalid) {
    failureMessage = "submissions.create.title.required"
    draft_title.value = submission.value.title
  } else if (newPubV$.value.maxLength.$invalid) {
    failureMessage = "submissions.create.title.max_length"
  }
  if (failureMessage !== false) {
    newStatusMessage("failure", t(failureMessage))
    return true
  }
  return false
}
```

The new standardized popup should look like the popup generation in option 2:
- Icon: Success
- Close UI: CLOSE
