### ISSUE TITLE
Implement Home Page Design

### ISSUE THREAD

**Issue by gmeben** [MESH-Research/Pilcrow#1806]
### Problem/Why
The new home page design has not been implemented into the application.

### Goal/What
Implement the new design of the home page.

### Solution/How
Update `Index.vue` to match the recently created [Adobe XD Home Page design](https://xd.adobe.com/view/29083090-64a2-49f0-9706-d41dbcfecbfb-7c5b/).

### To Do / Acceptance Criteria

- [x] Update `Index.vue`

### Review Checklist

- [x] The home page matches the design

### Accessibility Checklist

- [x] Text copy utilizes i18n.js and is contained within `<i18n-t>` tags
- [x] No new accessibility violations are introduced

**Comment by sattler9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pilcrow-Development-5ff39ba363391e0019713c87/issues/MESH-Research/Pilcrow/1806?planning-poker) with Zenhub @gmeben @vilagshe
