### ISSUE TITLE
Fix missing translations on publication setup / style criteria

### ISSUE THREAD

**Issue by wreality** [MESH-Research/Pilcrow#1807]
### Problem/Why
There are missing translations in the publication setup /style criteria page.  This is likely b/c the hint field is not provided and the Input component does not check before attempting to use this key in the translation.
![image.png](https://images.zenhubusercontent.com/5fe17935da86cae135bcd2ab/4e41ccfe-9ca1-4919-891a-95b806121341)

### Goal/What
There should not be warnings about missing translations in the console and the hint field should not be required

### Solution/How
Update the input component to check for the existence of a hint translation before including a hint on the input.

### To Do / Acceptance Criteria

- [x] Update component

### Review Checklist

- [x] Verify there are no longer missing translation errors on this page.

**Comment by gmeben** [comment]
For issues related to bugs, make sure to use the "Bug report" template.
