### ISSUE TITLE
Submission File Uploading

### ISSUE THREAD

**Issue by gmeben** [MESH-Research/Pilcrow#1846]
### Problem/Why
With the recent redesign of the Submissions page and submission intake form, file uploading has been temporarily disabled. This prevents users from being able to upload documents as submissions. 

### Goal/What
Re-enable uploads of files as part of the newly moved submission intake form. 

### Solution/How
Update the Submission Content page as necessary to support file uploading. Update the Vue template and the backend as necessary to enable a file from being included as part of a submission content creation update for a submission. 

### To Do / Acceptance Criteria

- [x] Update `SubmissionContent.vue` and backend for file uploading
- [x] Re-enable PHPUnit testing for uploads
- [x] Add Cypress testing for uploading a file as part of a submission

### Review Checklist

- [ ] A file can be uploaded and associated with a submission

### Accessibility Checklist

- [ ] Added copy uses plain language
- [ ] There are no newly introduced accessibility issues as detected by axe-core

**Comment by sattler9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pilcrow-Development-5ff39ba363391e0019713c87/issues/MESH-Research/Pilcrow/1846?planning-poker) with Zenhub @gmeben @wreality
