### ISSUE TITLE
Large List Appearance Inconsistency

### ISSUE THREAD

**Issue by gmeben** [MESH-Research/Pilcrow#1907]
**Describe the bug**
The appearances of large lists within the application are not consistent. They vary in whitespace and border usage. 

**Expected behavior**
Lists should be consistent and match the style of users lists as documented in the Style Guide:
https://github.com/MESH-Research/Pilcrow/wiki/Style-Guide---in-the-making#user-lists

**Screenshots**

![Screenshot of the All Users page showing a large list with no separating border between items and small paddings](https://github.com/MESH-Research/Pilcrow/assets/2668987/9ed362b7-a96f-43a6-b46b-4243c5f660d5)

![Screenshot of the Publications page showing a large list with separating borders between items and normal padding](https://github.com/MESH-Research/Pilcrow/assets/2668987/29321a51-21f8-419a-b62e-609dad9d100c)

**Comment by sattler9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pilcrow-Development-5ff39ba363391e0019713c87/issues/MESH-Research/Pilcrow/1907?planning-poker) with Zenhub @gmeben @vilagshe @wreality
