### ISSUE TITLE
Change Default Content for Publication Content Fields

### ISSUE THREAD

**Issue by gmeben** [MESH-Research/Pilcrow#1915]
The default descriptive content for publications that appears on the home pages of publications and the submission creation page uses lorem ipsum. 

Change this so that it uses a coherent description of the purpose of these placeholders in English.

**Review Checklist**

* Seeded content has been updated 
* Necessary testing has been updated (if applicable)

**Accessibility Checklist**

* Changed text has a font size of at least 16px
* Changed text uses plain language

**Comment by sattler9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pilcrow-Development-5ff39ba363391e0019713c87/issues/MESH-Research/Pilcrow/1915?planning-poker) with Zenhub @gmeben @vilagshe @wreality
