### ISSUE TITLE
Don't Present Status Changing Options to Reviewers

### ISSUE THREAD

**Issue by gmeben** [MESH-Research/Pilcrow#1916]
Although attempts at status changes from reviewers are rejected, the "Status Options" widget remains visible and interactive to reviewers, which can result in confusion and clutters the user interface. 

![Screenshot showing that the "Status Options" widget remains visible to a reviewer](https://images.zenhubusercontent.com/5ff7670b9384a948b4663b2d/0bc8dee5-90c7-454d-867d-d3022dcad42c)

Conditionally display the  "Status Options" widget so that it does not appear for reviewers. 

**Review Checklist**

* Necessary frontend unit testing has been updated and/or added
* Necessary integration testing has been updated and added
* Documentation has been updated to reflect new changes

**Accessibility Checklist**

* No new color contrast issues are introduced

**Comment by sattler9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pilcrow-Development-5ff39ba363391e0019713c87/issues/MESH-Research/Pilcrow/1916?planning-poker) with Zenhub @gmeben @vilagshe @wreality @stephanievaskomsu

**Comment by gmeben** [comment]
I discovered there's faulty behavior as far as changing the statuses of submissions. It does not accurately reflect the diagram on Miro that's been known since at least before July 8th, 2022: https://miro.com/app/board/o9J_l654lxo=/?moveToWidget=3458764550697641481&cot=14

Submissions with a state of "Resubmission Requested" or "Archived" should be allowed to be changed to "Deleted" as the diagram shows. Currently, these state changes are disabled for such submissions in the application. 

For now, I'm going to elect to completing this work without increasing scope and fixing this now because I anticipate the fix will warrant heavy refactoring so that the status changing logic is all controlled from one central place and not spread between two different Vue file as nested template logic.
