### ISSUE TITLE
Website Input Format Is Too Demanding

### ISSUE THREAD

**Issue by gmeben** [MESH-Research/Pilcrow#1922]
When attempting to update the website field on the profile details page, the website input requires a user to input `http://www` in order to be accepted. This creates an obstacle that's too demanding for users.

![Screenshot of the Profile Details page showing that google.com is considered an invalid website](https://images.zenhubusercontent.com/5ff7670b9384a948b4663b2d/0894c551-cfbc-42c4-94b1-a42466168485)

Appropriate sanitization should be applied on this input to prevent JavaScript injections. Appropriate whitespace trimming should also be applied. 

**To-do**

* Update the rules for a valid website in `profileMetadata.js`

**Review Checklist**

* `google.com` is accepted as a valid URL in the website field
* Necessary backend unit testing has been added
* Necessary frontend unit testing has been added
* Necessary integration testing has been added
* Documentation has been updated to reflect new changes

**Comment by sattler9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pilcrow-Development-5ff39ba363391e0019713c87/issues/MESH-Research/Pilcrow/1922?planning-poker) with Zenhub @gmeben @stephanievaskomsu @vilagshe @wreality

**Comment by wreality** [comment]
@gmeben i was thinking about this more tonight. The most important thing we should do besides the work here to sanitize values on the way in is to be sure we pass them through JavaScript’s url constructor on the way out when we’re going to put the link in an href.

**Comment by gmeben** [comment]
@wreality I noted in [the pull request](https://github.com/MESH-Research/Pilcrow/pull/1974) that Laravel handles sanitization by default. Is there some kind of other sanitization we should be doing client-side? 

The new regex rejects all of the following values:

```
console.log('hi')
javascript:alert('hi')
google.<script>alert("Hello World")</script>
eval()
Function()
setTimeout()
setInterval()
setImmediate()
execCommand()
execScript()
msSetImmediate()
range.createContextualFragment()
crypto.generateCRMFRequest()
```

We can totally use the URL constructor when we start presenting these values in anchors on the client.

**Comment by gmeben** [comment]
The effort value of this issue ended up feeling more like an `8` or `13`.
