### ISSUE TITLE
Dark Mode Toggle Widget Does Not Accurately Reflect Toggle State

### ISSUE THREAD

**Issue by gmeben** [MESH-Research/Pilcrow#1923]
**Describe the bug**
When in light mode, the default toggle state of the dark mode toggle widget is set to the "Dark" setting by default, which is inaccurate and misleading. 

**To Reproduce**
1. Make sure your device's display settings are set to Light mode
2. Visit the Review page of any submission
3. Note that the toggle widget incorrectly reports that the current state is Dark mode
    * Clicking the toggle will result in the toggle not changing. Subsequent clicks change it.

**Expected behavior**
If the user is in light mode, the toggle should correctly reflect this at initial page load. 

**Screenshots**
[Screenshot of the Review page while in Light mode. The toggle switch is labeled "Dark Mode"](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBblZTIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a3357244b1cf4e222c3a5414204ce785b8c4b692/dark-mode.png)

**Comment by sattler9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pilcrow-Development-5ff39ba363391e0019713c87/issues/MESH-Research/Pilcrow/1923?planning-poker) with Zenhub @gmeben @vilagshe @wreality
