### ISSUE TITLE
Backend Protection for Comment Modification

### ISSUE THREAD

**Issue by gmeben** [MESH-Research/Pilcrow#1924]
While there are protections against comment modification on the frontend, it is still possible for a comment to be modified by an authenticated user sending post requests to the GraphQL endpoint directly for comments that don't belong to them. 

Add protection to the backend so that this cannot be done. 

**Review Checklist** 

* Necessary backend unit testing has been added 
* Necessary unit testing has been added/updated

**Comment by sattler9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pilcrow-Development-5ff39ba363391e0019713c87/issues/MESH-Research/Pilcrow/1924?planning-poker) with Zenhub @gmeben @vilagshe @wreality
