### ISSUE TITLE
Preview Submission Before Submitting

### ISSUE THREAD

**Issue by gmeben** [MESH-Research/Pilcrow#1925]
**Describe the problem and/or goal**

When a submitter drafts the content of a submission, they are not able to preview the content as it would appear on the Review page before submitting. 

Add functionality that allows a user to preview a draft submission before submitting. This should open an interface that resembles the Review page, but with no comment functionality. This previewing should be available for any submission with a status of Draft. Submissions with a status of Initially Submitted should only be viewed.

**Review Checklist**

* Previewing has been added
* Necessary integration testing has been added
* Documentation has been updated to reflect new changes

**Accessibility Checklist**

* No new color contrast issues are introduced
* Added text has a font size of at least 16px
* Added text uses plain language

**Comment by sattler9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pilcrow-Development-5ff39ba363391e0019713c87/issues/MESH-Research/Pilcrow/1925?planning-poker) with Zenhub @gmeben @vilagshe @wreality
