### ISSUE TITLE
Add Button to Scroll to Overall Comments

### ISSUE THREAD

**Issue by gmeben** [MESH-Research/Pilcrow#1926]
**Describe the problem and/or goal**
When a user wants to access the overall comments beneath a submission, a user must scroll the entirety of the submission to access them. This also poses challenges that prevent a user from being able to easily draft an overall comment while reading through a submission. 

Update the interface of the Review page so that there is a button that appears as one of the first elements on the page that, when clicked, automatically scrolls the viewport to the Overall Comments section.

**Review Checklist**

* A button appears on the Review page that instantly takes a user to the Overall Comments section
* Necessary integration testing has been added
* Documentation has been updated to reflect new changes

**Accessibility Checklist**

* No new color contrast issues are introduced
* Added text has a font size of at least 16px
* Added text uses plain language

**Comment by sattler9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pilcrow-Development-5ff39ba363391e0019713c87/issues/MESH-Research/Pilcrow/1926?planning-poker) with Zenhub @gmeben @vilagshe @wreality

**Comment by vilagshe** [comment]
Buttons are added:
- Button that scrolls the user to the overall comments section
- Button that scrolls the user to the overall comment editor

Work in progress:
- Focus the overall comment editor

**Comment by vilagshe** [comment]
I think I have the Cypress test in a place where it's ready, but I have run across another issue trying to run Cypress.
<img width="449" alt="image" src="https://github.com/MESH-Research/Pilcrow/assets/108834493/3458aef3-5a52-4c46-86ef-68135442e679">

**Comment by gmeben** [comment]
@vilagshe  Run `lando cypress install` instead

**Comment by wreality** [comment]
@vilagshe Yay!!!! Congrats!!! 🎉
