### ISSUE TITLE
Inconsistent Menu Options and Names for Account/Profile Pages

### ISSUE THREAD

**Issue by gmeben** [MESH-Research/Pilcrow#1929]
The dropdown menu in the main navigational bar only has a link to the "My Account" page. It does not include a menu item for the "Profile Information" page. The naming of these pages is also inconsistent throughout the application. 

The "Profile Information" and "Account Profile" pages should be renamed.

- [x] Change "Account Info" to "Login and Password"
- [x] Change "Profile Info" to "Profile"
- [x] Remove "X" from dropdown menu and add "Profile" and "Login and Password" as dropdown menu options
- [x] Flip order to "Profile" and "Login and Password" on dashboard

**Review Checklist**

* Necessary integration testing has been updated

**Accessibility Checklist**

* No new color contrast issues are introduced
* Changed text has a font size of at least 16px
* Changed text uses plain language

**Comment by gmeben** [comment]
I opted to keep this as a separate issue from #1945 because it deals with areas of the site outside of the Account/Profile pages. If others would rather that this be merged into #1945, then feel free to do so.

**Comment by sattler9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pilcrow-Development-5ff39ba363391e0019713c87/issues/MESH-Research/Pilcrow/1929?planning-poker) with Zenhub @gmeben @vilagshe @wreality
