### ISSUE TITLE
Commenting: Click on Comment to go to comment location in text/submission

### ISSUE THREAD

**Issue by stephanievaskomsu** [MESH-Research/Pilcrow#1936]
**Describe the problem and/or goal**
Currently, a user on the Review page can click chat bubble icons that denote inline comments and the respective inline comment will be scrolled to and highlighted. However, there is no way to click on an inline comment be scrolled to its corresponding highlight in the submission. This should be bidirectional behavior. 

Add an interactive element on inline comments that enables a user to scroll to and highlight an inline comment's highlight from the inline comment itself. 

**Review Checklist**
* Add interactive element to inline comments
* Necessary integration testing has been added
* Documentation has been updated to reflect new changes

**Accessibility Checklist**
* No new color contrast issues are introduced
* Added or changed text has a font size of at least 16px
* Added or changed text uses plain language

**Comment by sattler9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pilcrow-Development-5ff39ba363391e0019713c87/issues/MESH-Research/Pilcrow/1936?planning-poker) with Zenhub @gmeben @vilagshe @wreality

**Comment by gmeben** [comment]
Feature Request: https://feedback.pilcrow.dev/posts/5/enable-linking-from-inline-comments-back-to-highlighted-text
