### ISSUE TITLE
Resolve Problems with Account/Profile Pages

### ISSUE THREAD

**Issue by gmeben** [MESH-Research/Pilcrow#1945]
On the Profile page, "Professional Title" was found to be confusing for users. It should be changed to "Position Title". 

Academia.edu has been found to operate with values that are incompatible with Mesh Research's, so its field on the Profile page should be removed. 

In the "Academic Profiles" section on the Profile page, the icons for the corresponding fields in this section are broken links. These need to be fixed. 

The "Preview Public Profile" link on the Account and Profile pages is nonfunctional. It should be removed. Similarly, the ?? placeholders on these pages are also nonfunctional and should be removed.

* [x] Change "Professional Title" to "Position Title"
* [x] Remove the input field for Academia.edu
* [x] Fix the broken image links in the Academic Profiles section
* [x] Remove "Preview Public Profile
* [x] Remove ?? placeholders

**Review Checklist**

* Necessary backend unit testing has been updated
* Necessary frontend unit testing has been updated
* Necessary integration testing has been updated

**Accessibility Checklist**

* No new color contrast issues are introduced
* Changed text has a font size of at least 16px
* Changed text uses plain language

**Comment by sattler9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pilcrow-Development-5ff39ba363391e0019713c87/issues/MESH-Research/Pilcrow/1945?planning-poker) with Zenhub @gmeben @vilagshe @wreality
