### ISSUE TITLE
Submission Workflow Design Sprint

### ISSUE THREAD

**Issue by stephanievaskomsu** [MESH-Research/Pilcrow#1958]
**Describe the problem and/or goal**
We need to create a new submission workflow based on feedback from usability testing. 

**(optional) Describe how to complete this**
We will start by meeting at 3PM during team time on Monday, September 11 to go over feedback and SEV's initial mockup and start creating a new set of wireframes to share w/ PPJ. Looking to complete work on an initial version of this by 9/15/2023.

**Comment by sattler9** [comment]
Was shown to PPJ. We've received feedback from multiple areas. Fairly set on what we're changing.
