### ISSUE TITLE
Add a list of the types of documents accepted for submission

### ISSUE THREAD

**Issue by sattler9** [MESH-Research/Pilcrow#2046]
To aid the submitter, it would be kind and helpful to let them know which document types are accepted by Pilcrow prior to trying to submit a file. This will prevent frustration or the belief that Pilcrow is broken when a type that is not accepted is used in the submission process and fails.

**Describe the solution you'd like**
Add a list of the document types that Pilcrow accepts to the Submission Content page in the upload box.

<img width="1569" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelNxQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f7f07afa2f8620f6bb610e626683615a62f2864c/Screenshot%202024-01-08%20at%203.43.51%E2%80%AFPM.png" alt="Screenshot 2024-01-08 at 3.43.51 PM.png" />

This is associated with the feature request at https://feedback.pilcrow.dev/posts/19/upload-types

**Comment by sattler9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pilcrow-Development-5ff39ba363391e0019713c87/issues/MESH-Research/Pilcrow/2046?planning-poker) with Zenhub @gmeben @sattler9 @vilagshe @wreality

**Comment by gmeben** [comment]
Related issue: https://github.com/MESH-Research/Pilcrow/issues/517
