### ISSUE TITLE
Add Counts of Replies to Comment Threads

### ISSUE THREAD

**Issue by gmeben** [MESH-Research/Pilcrow#2070]
When encountering a thread of inline or overall comments, there's no explicit indicator for how many replies a thread contains. There's also no explicit indicator for any newly added replies. These deficiencies make it difficult for users to recognize at a glance of new comment activity. 

Add a count of how many replies a comment thread contains that's visible before a thread is expanded with the "Show Replies" button.

**Review Checklist**

* Numeric indicators of replies within threads are visible
* Necessary frontend unit testing has been added

**Accessibility Checklist**

* No new color contrast issues are introduced
* Added text has a font size of at least 16px
* Added text uses plain language

**Comment by gmeben** [comment]
Feature Request: https://feedback.pilcrow.dev/posts/8/way-to-denote-an-updated-comment

**Comment by sattler9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pilcrow-Development-5ff39ba363391e0019713c87/issues/MESH-Research/Pilcrow/2070?planning-poker) with Zenhub @gmeben @vilagshe @wreality
