### ISSUE TITLE
Add Indicators For New Replies

### ISSUE THREAD

**Issue by gmeben** [MESH-Research/Pilcrow#2071]
If another user replies to a comment, there is no explicit indicator that the reply was newly added or that the reply has been seen before.

Add functionality to detect whether or not a reply has been viewed by a user and show some visual indication of such.  Perhaps this should be tied into a corresponding notification being read?

**Review Checklist**

* Visual indicators of a newly added replies are visible
* Necessary frontend unit testing has been added
* Necessary integration testing has been added

**Accessibility Checklist**

* No new color contrast issues are introduced
* Changed text has a font size of at least 16px
* Changed text uses plain language

**Comment by gmeben** [comment]
Feature Request: https://feedback.pilcrow.dev/posts/8/way-to-denote-an-updated-comment

**Comment by sattler9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pilcrow-Development-5ff39ba363391e0019713c87/issues/MESH-Research/Pilcrow/2071?planning-poker) with Zenhub @gmeben @vilagshe @wreality
