### ISSUE TITLE
Update Submissions Tables with Date and Username

### ISSUE THREAD

**Issue by gmeben** [MESH-Research/Pilcrow#2074]
Currently, submissions presented within submission tables don't show when they were submitted or by whom. Publication Names has a column, which may not be useful to Pilcrow instances where only one publication will exist. 

Add the following columns to Submission Tables:

* Submitted By: with a value of the name or username of the user who is listed as the submitter
* Submitted On: with a relative timestamp of when the submission was submitted

**Review Checklist**

* Columns to submission tables are added
* Necessary frontend unit testing has been added

**Accessibility Checklist**

* No new color contrast issues are introduced
* Changed text has a font size of at least 16px
* Changed text uses plain language

**Comment by gmeben** [comment]
The added columns are likely going to make it so that the width of submission tables will exceed the viewports of devices most of the time, making the "Actions" column only accessible with horizontal scrolling. 

Question for this issue: 

1. Does it make sense to add functionality that allows a user to specify which columns are visible? 
    - Pros: users are empowered by the interface, table-width problems are eliminated
    - Cons: could be costly to design and implement appropriate components, existing tests will need to be updated
    - This could be done by:
        - Storing this preference information in the database
            - Pro: user preferences are saved regardless of device accessing Pilcrow
            - Con: somewhat costly in that an appropriate database schema will need to be designed and implemented
        - Using cookies and storing this preference information client-side
            - Pros: relatively inexpensive to implement
            - Cons: user preferences are relative to the device accessing Pilcrow, has GDPR concerns because cookies are being used

**Comment by sattler9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pilcrow-Development-5ff39ba363391e0019713c87/issues/MESH-Research/Pilcrow/2074?planning-poker) with Zenhub @gmeben @vilagshe @wreality

**Comment by gmeben** [comment]
A separate issue will be created to address any reflow problems or empowering users to modify the appearance of the interface with regard to submission tables.
