### ISSUE TITLE
Password Reset - A user should be able to recover their account.

### ISSUE THREAD

**Issue by wreality** [MESH-Research/Pilcrow#21]
**Problem/Why**

A user cannot recover their account if they forget their password.

---

**Goal/What**

The user should be able to visit a page in the application, enter their email, and have an email sent to them with a link to reset their password.  Upon visiting the link, the user should be prompted to enter a new password.

---

**Solution/How**
Create a Contract to reset password "Illuminate\Contracts\Auth\CanResetPassword" using lando artisan make:contract CanResetPassword
Generate a reset token and update the db with the reset token.

**https://laravel.com/docs/8.x/passwords**

---

### To Do / Acceptance Criteria

- [x] Update Vue templates to handle user interactions for requesting a password reset
- [x] Update backend to handle password reset requests
- [x] Add functionality to backend to send a user a password reset email
- [x] Update Vue templates to submit password resets and handle server responses to password resets
- [x] Add validation for password reset data

### Review Checklist

- [ ] A user can request a password reset
- [ ] The user is sent an email to follow to reset their password.
- [ ] The link presents as form to submit a new password
- [ ] The password is reset

### Accessibility Checklist

- [ ] New interactive elements can be accessed solely by keyboard
- [ ] New interactive elements are discoverable by a screen reader
- [ ] Pages pass axe DevTools accessibility testing

**Comment by sattler9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCR-5ff39ba363391e0019713c87/issues/MESH-Research/CCR/21?planning-poker) with ZenHub @amareshjoshi @gmeben @Sruthin86 @wreality

**Comment by sattler9** [comment]
Email will have standard, non-customizable language.

**Comment by gmeben** [comment]
This ended up feeling more like a `5` than a `3` in terms of estimation.
