### ISSUE TITLE
Set permissions for reviewer assignments on Submission Details page.

### ISSUE THREAD

**Issue by Sruthin86** [MESH-Research/Pilcrow#492]
### Problem/Why
The frontend for submissions detail page exists and currently there are no restrictions in place for reviewer assignment.

### Goal/What
Change the access control of the route for the submission details page so that a user's access to the page is allowed under any of these conditions: 

* A user is assigned to the submission
    * This applies to Submitters, Reviewers, and Review Coordinators 
* A user has one of the following roles
    * Editor
    * Publication Administrator
    * Application Administrator

Protect the endpoint of the GraphQL mutation so that any requests received to the backend for reviewer assignment also follow the same access control rules outlined above, with the exception that review coordinators are the only submission-relative role that can assign reviewers.

### Solution/How
Create demo accounts for the roles that are missing representation. Add necessary router guards to protect page access. Add necessary backend code to protect mutation access. 

### To Do / Acceptance Criteria

- [x] Create seed users for Review Coordinators, Editors, and Publication Administrators
- [x] Add router guard code to enforce access control on the submission details page
- [x] Add backend code as necessary to enforce access control on reviewer assignments
- [x] Add/fix PHP unit testing to check for proper backend restrictions
- [x] Add/fix Jest and/or Cypress testing to check for proper client restrictions

### Review Checklist

- [x] Reviewer assignment is restricted based on the rules outlined above in the Goal section
- [x] Page access is restricted based on the rules outlined above in the Goal section
- [x] All new and existing tests pass

**Comment by gmeben** [comment]
The client side work on this issue is blocked by #496 but the backend work is not.

**Comment by Sruthin86** [comment]
**Work completed**
* Added demo accounts for Review Coordinators, Editors, and Publication Administrators, Review Coordinators, Editors, Publication.

**Work in progress**
* Figure out the front end permissions which controls page access. In addition to the privileged roles we want the owner of the submission to access the page

**Comment by gmeben** [comment]
These are the cases that need to be tested for to prove the OR logic gate on the intended access control:

1. Application Administrator, assigned to submission
2. Application Administrator, not assigned to submission
3. Not an Application Administrator, assigned to submission
4. Not an Application Administrator, not assigned to submission
