### ISSUE TITLE
Basic User Access

### ISSUE THREAD

**Issue by wreality** [MESH-Research/Pilcrow#83]
**Problem/Why**

There are a number of necessary core features that are not yet completed and expected by all to be included in an initial release of the application. 

---

**Goal/What**

Address and implement features to handle the following:

1. **User authentication - sub-epic**
   1. Internal - connected frontend and backend for authentication
   1. **On-Hold** External connections - authentication providers
      1. Google
      1. Twitter
      1. Facebook
   1. Create a system that allows users to authenticate. Its sign in functionality should:
      1. Accept email and custom password pairs.
      1. Accept logins from external providers (like Google).
      1. Notify users if their account is locked.
      1. Provide options to reset password when authentication fails.
1. **User registration - sub-epic**
   1. Improve user login and registration
   1. Add missing unit tests for creatUser mutation
1. **User Profiles - sub-epic** 
   1. Identify what metadata is needed
   1. Expansion of user profiles - associate metadata with user
   1. Updating user information

---

**Solution/How**

Resolve the child issues related to this Epic.
 
> Trello Source: https://trello.com/c/d6gi4IcT

**Comment by sattler9** [comment]
removed ticket #145 as logging out across all devices is an enhanced feature. Having the ability to log out per device is sufficient for authentication.
