### ISSUE TITLE
Authentication - External Identity Provider Authentication

### ISSUE THREAD

**Issue by wreality** [MESH-Research/Pilcrow#85]
**Problem/Why**

The application requires users to create a new set of credentials. Users may find having to create and manage a new set of credentials for Pilcrow to be cumbersome and may prevent them from using Pilcrow up altogether. Users may be disappointed upon discovering that they are unable to authenticate on Pilcrow using their (for example) Google account.

**Goal/What**

Implement functionality that allows sign-ins from external accounts (ex: Google, Twitter, Facebook). Users should be able to authenticate with those chosen external identity providers.

**Solution/How**
 
* [x] Update Login page template to support external auth
* [x] Use Laravel Socialite to enable external identity provider authentication. 
* Necessary backend unit testing has been added
* Necessary frontend unit testing has been added
* Necessary integration testing has been added
* [x] Documentation has been updated to reflect new changes
 
**Review List**

* No new color contrast issues are introduced
* Added or changed text has a font size of at least 16px
* Added or changed text uses plain language

> Trello Source: https://trello.com/c/Kw9ElgRE

**Comment by gmeben** [comment]
Video tutorial: https://www.youtube.com/watch?v=FLsSEV5ulD4

**Comment by gmeben** [comment]
Integrating Google Sign-In into your web app: https://developers.google.com/identity/sign-in/web/sign-in

**Comment by sattler9** [comment]
Documented in Feature request: https://feedback.pilcrow.dev/posts/1/allow-users-to-login-create-accounts-using-google-and-orcid and connected to #88

**Comment by gmeben** [comment]
The work in this issue overlaps with #88 more than I originally thought. Handling OAuth correctly means that both registration and authentication will be necessary.
